# Generated by Django 3.1.1 on 2020-09-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='eur',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='currency',
            name='usd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
