# Generated by Django 3.0.5 on 2020-09-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200912_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_dol',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_eur',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_rub',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.User'),
        ),
    ]
