# Generated by Django 3.1 on 2020-10-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_money_usd_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='usd_sale',
        ),
        migrations.AddField(
            model_name='money',
            name='Покупка банком',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='money',
            name='Продажа банком',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
