# Generated by Django 3.1 on 2020-09-29 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='dollar',
        ),
        migrations.AddField(
            model_name='money',
            name='eur',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='money',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 9, 50, 10, 837020, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='money',
            name='usd',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
