# Generated by Django 3.1 on 2020-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201001_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='Покупка банком',
        ),
        migrations.RemoveField(
            model_name='money',
            name='Продажа банком',
        ),
        migrations.AddField(
            model_name='money',
            name='USD Покупка банком',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='money',
            name='USD Продажа банком',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
