# Generated by Django 3.0.5 on 2020-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200912_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_dol',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_eur',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=16),
        ),
    ]
