# Generated by Django 3.0.5 on 2020-09-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200912_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='name_credit',
            field=models.CharField(default='For phone', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
