# Generated by Django 3.1 on 2020-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200915_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='balance_rub',
        ),
        migrations.AddField(
            model_name='balance',
            name='rub',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
