# Generated by Django 3.1 on 2020-09-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200918_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.DecimalField(decimal_places=2, max_digits=5)),
                ('EUR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('USD_P', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
